package parser

const LEFT_PAREN = "("
const RIGHT_PAREN = ")"
const LEFT_BRACE = "["
const RIGHT_BRACE = "]"
const COMMA = ","
const DOT = "."
const MINUS = "-"
const PLUS = "+"
const SEMICOLON = ";"
const SLASH = "/"
const STAR = "*"
const BANG = "!"
const BANG_EQUAL = "!="
const EQUAL = "="
const EQUAL_EQUAL = "=="
const GREATER = ">"
const GREATER_EQUAL = ">="
const LESS = "<"
const LESS_EQUAL = "<="
